# Generated by Django 6.0 on 2025-12-08 15:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('gateway', models.CharField(choices=[('CLICK', 'Click'), ('PAYME', 'Payme'), ('UZUM', 'Uzum Pay')], help_text='Payment gateway name', max_length=20, unique=True, verbose_name='gateway')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this gateway is currently active', verbose_name='active')),
                ('merchant_id', models.CharField(blank=True, help_text='Merchant/Vendor ID', max_length=255, verbose_name='merchant ID')),
                ('secret_key', models.CharField(blank=True, help_text='API secret key (encrypt in production!)', max_length=255, verbose_name='secret key')),
                ('api_url', models.URLField(blank=True, help_text='Payment gateway API endpoint', verbose_name='API URL')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Additional gateway-specific settings', verbose_name='configuration')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Gateway commission percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='commission percentage')),
            ],
            options={
                'verbose_name': 'payment gateway config',
                'verbose_name_plural': 'payment gateway configs',
                'db_table': 'payment_gateway_configs',
                'indexes': [models.Index(fields=['gateway'], name='payment_gat_gateway_a6adf1_idx'), models.Index(fields=['is_active'], name='payment_gat_is_acti_983b05_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique transaction identifier', max_length=100, unique=True, verbose_name='transaction ID')),
                ('transaction_type', models.CharField(choices=[('COURSE_PURCHASE', 'Course Purchase'), ('REFUND', 'Refund'), ('AUTHOR_PAYOUT', 'Author Payout')], default='COURSE_PURCHASE', help_text='Type of transaction', max_length=20, verbose_name='transaction type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in UZS', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('currency', models.CharField(default='UZS', help_text='Currency code', max_length=3, verbose_name='currency')),
                ('gateway', models.CharField(choices=[('CLICK', 'Click'), ('PAYME', 'Payme'), ('UZUM', 'Uzum Pay')], help_text='Payment gateway used', max_length=20, verbose_name='payment gateway')),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment gateway', max_length=255, verbose_name='gateway transaction ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Transaction status', max_length=20, verbose_name='status')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction data from gateway', verbose_name='metadata')),
                ('error_message', models.TextField(blank=True, help_text='Error message if transaction failed', verbose_name='error message')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When transaction completed successfully', null=True, verbose_name='completed at')),
                ('course', models.ForeignKey(blank=True, help_text='Course being purchased (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='courses.course', verbose_name='course')),
                ('enrollment', models.ForeignKey(blank=True, help_text='Related enrollment record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='courses.courseenrollment', verbose_name='enrollment')),
                ('payee', models.ForeignKey(help_text='User receiving the payment (author or platform)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL, verbose_name='payee')),
                ('payer', models.ForeignKey(help_text='User who made the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to=settings.AUTH_USER_MODEL, verbose_name='payer')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to refund in UZS', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='refund amount')),
                ('reason', models.TextField(help_text='Student reason for requesting refund', verbose_name='reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', help_text='Refund request status', max_length=20, verbose_name='status')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When refund was reviewed', null=True, verbose_name='reviewed at')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes or rejection reason', verbose_name='admin notes')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='courses.courseenrollment', verbose_name='enrollment')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_refunds', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to=settings.AUTH_USER_MODEL, verbose_name='student')),
                ('original_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests', to='payments.transaction', verbose_name='original transaction')),
                ('refund_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_for', to='payments.transaction', verbose_name='refund transaction')),
            ],
            options={
                'verbose_name': 'refund request',
                'verbose_name_plural': 'refund requests',
                'db_table': 'refund_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Platform commission percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='commission percentage')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this commission rule is active', verbose_name='active')),
                ('effective_from', models.DateTimeField(help_text='When this commission rate becomes effective', verbose_name='effective from')),
                ('effective_until', models.DateTimeField(blank=True, help_text='When this commission rate expires (null = no expiry)', null=True, verbose_name='effective until')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this commission rule', verbose_name='notes')),
                ('category', models.ForeignKey(blank=True, help_text='Specific category (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='courses.category', verbose_name='category')),
                ('course', models.ForeignKey(blank=True, help_text='Specific course (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='courses.course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'platform commission',
                'verbose_name_plural': 'platform commissions',
                'db_table': 'platform_commissions',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['course', 'is_active'], name='platform_co_course__e46f97_idx'), models.Index(fields=['category', 'is_active'], name='platform_co_categor_dccb42_idx'), models.Index(fields=['effective_from'], name='platform_co_effecti_ad07f5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_id'], name='transaction_transac_5011c8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payer', '-created_at'], name='transaction_payer_i_693f54_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payee', '-created_at'], name='transaction_payee_i_9b72f2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_505a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['gateway'], name='transaction_gateway_4e5b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['course'], name='transaction_course__d6118e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-created_at'], name='transaction_created_cf5536_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['student', '-created_at'], name='refund_requ_student_0f2bd8_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['status'], name='refund_requ_status_2691a2_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['enrollment'], name='refund_requ_enrollm_7c06fa_idx'),
        ),
    ]
