# Generated by Django 6.0 on 2025-12-08 10:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('phone_number', models.CharField(help_text='Required. Format: +998XXXXXXXXX', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+998XXXXXXXXX'", regex='^\\+998[0-9]{9}$')], verbose_name='phone number')),
                ('email', models.EmailField(blank=True, help_text='Optional email address', max_length=254, null=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('AUTHOR', 'Author'), ('ADMIN', 'Admin')], default='STUDENT', help_text='User role in the platform', max_length=10, verbose_name='role')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active')),
                ('phone_verified', models.BooleanField(default=False, help_text='Designates whether phone number has been verified.', verbose_name='phone verified')),
                ('email_verified', models.BooleanField(default=False, help_text='Designates whether email has been verified.', verbose_name='email verified')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('phone_number', models.CharField(db_index=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+998XXXXXXXXX'", regex='^\\+998[0-9]{9}$')], verbose_name='phone number')),
                ('otp_code', models.CharField(help_text='6-digit verification code', max_length=6, verbose_name='OTP code')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the OTP has been successfully verified', verbose_name='verified')),
                ('expires_at', models.DateTimeField(help_text='When this OTP expires', verbose_name='expires at')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of verification attempts made', verbose_name='verification attempts')),
            ],
            options={
                'verbose_name': 'phone verification',
                'verbose_name_plural': 'phone verifications',
                'db_table': 'phone_verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', '-created_at'], name='phone_verif_phone_n_cef185_idx'), models.Index(fields=['expires_at'], name='phone_verif_expires_efa46d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('provider', models.CharField(choices=[('GOOGLE', 'Google'), ('TELEGRAM', 'Telegram')], help_text='Social authentication provider', max_length=20, verbose_name='provider')),
                ('provider_user_id', models.CharField(help_text='Unique user ID from the provider', max_length=255, verbose_name='provider user ID')),
                ('access_token', models.TextField(blank=True, help_text='OAuth access token (encrypted in production)', verbose_name='access token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token (encrypted in production)', verbose_name='refresh token')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True, verbose_name='token expires at')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional data from provider (profile info, etc.)', verbose_name='extra data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_auths', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'social authentication',
                'verbose_name_plural': 'social authentications',
                'db_table': 'social_auths',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='users_phone_n_a3b1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='socialauth',
            index=models.Index(fields=['user', 'provider'], name='social_auth_user_id_762ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='socialauth',
            index=models.Index(fields=['provider', 'provider_user_id'], name='social_auth_provide_5b6f36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialauth',
            unique_together={('provider', 'provider_user_id')},
        ),
    ]
