# Generated by Django 6.0 on 2025-12-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional email address for login and notifications', max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
