# Generated by Django 6.0 on 2025-12-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='User age', null=True, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram user ID for bot notifications', null=True, unique=True, verbose_name='telegram ID'),
        ),
    ]
