# Generated by Django 6.0 on 2025-12-08 10:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Student profile picture', null=True, upload_to='students/profiles/', verbose_name='profile picture')),
                ('bio', models.TextField(blank=True, help_text='Student bio or learning goals', verbose_name='bio')),
                ('enrolled_courses_count', models.PositiveIntegerField(default=0, help_text='Total courses enrolled in', verbose_name='enrolled courses')),
                ('completed_courses_count', models.PositiveIntegerField(default=0, help_text='Total courses completed', verbose_name='completed courses')),
                ('total_watch_time_hours', models.PositiveIntegerField(default=0, help_text='Total video watch time in hours', verbose_name='total watch time')),
                ('certificates_earned', models.PositiveIntegerField(default=0, help_text='Number of completion certificates earned', verbose_name='certificates earned')),
            ],
            options={
                'verbose_name': 'student profile',
                'verbose_name_plural': 'student profiles',
                'db_table': 'student_profiles',
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('watch_duration_seconds', models.PositiveIntegerField(default=0, help_text='How long student watched in this session (seconds)', verbose_name='watch duration')),
                ('percentage_watched', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of video watched in this session', max_digits=5, verbose_name='percentage watched')),
                ('session_id', models.CharField(blank=True, help_text='Session identifier for grouping watch events', max_length=100, verbose_name='session ID')),
                ('device_type', models.CharField(blank=True, help_text='Device used for watching (desktop, mobile, tablet)', max_length=50, verbose_name='device type')),
            ],
            options={
                'verbose_name': 'watch history',
                'verbose_name_plural': 'watch history',
                'db_table': 'watch_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('certificate_id', models.CharField(help_text='Unique certificate identifier for verification', max_length=100, unique=True, verbose_name='certificate ID')),
                ('certificate_file', models.FileField(blank=True, help_text='Generated PDF certificate', null=True, upload_to='certificates/', verbose_name='certificate file')),
                ('issued_at', models.DateTimeField(auto_now_add=True, help_text='When certificate was issued', verbose_name='issued at')),
                ('verification_url', models.URLField(blank=True, help_text='Public URL to verify certificate authenticity', verbose_name='verification URL')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course', verbose_name='course')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='courses.courseenrollment', verbose_name='enrollment')),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
                'db_table': 'certificates',
                'ordering': ['-issued_at'],
            },
        ),
    ]
