# Generated by Django 6.0 on 2025-12-08 10:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance available for withdrawal in UZS', max_digits=12, verbose_name='available balance')),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance pending (not yet available for withdrawal) in UZS', max_digits=12, verbose_name='pending balance')),
                ('lifetime_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total earnings all-time in UZS', max_digits=12, verbose_name='lifetime earnings')),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount withdrawn in UZS', max_digits=12, verbose_name='total withdrawn')),
            ],
            options={
                'verbose_name': 'author balance',
                'verbose_name_plural': 'author balances',
                'db_table': 'author_balances',
            },
        ),
        migrations.CreateModel(
            name='AuthorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payout amount in UZS', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CLICK', 'Click'), ('PAYME', 'Payme'), ('UZUM', 'Uzum Pay')], help_text='Method for receiving payout', max_length=20, verbose_name='payout method')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Payout request status', max_length=20, verbose_name='status')),
                ('payment_details', models.JSONField(default=dict, help_text='Bank account, card number, or wallet info', verbose_name='payment details')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When payout was processed', null=True, verbose_name='processed at')),
                ('transaction_id', models.CharField(blank=True, help_text='External transaction reference', max_length=255, verbose_name='transaction ID')),
                ('notes', models.TextField(blank=True, help_text='Admin notes or rejection reason', verbose_name='notes')),
            ],
            options={
                'verbose_name': 'author payout',
                'verbose_name_plural': 'author payouts',
                'db_table': 'author_payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('bio', models.TextField(blank=True, help_text='Author biography and expertise', verbose_name='bio')),
                ('profile_picture', models.ImageField(blank=True, help_text='Author profile picture', null=True, upload_to='authors/profiles/', verbose_name='profile picture')),
                ('expertise', models.CharField(blank=True, help_text='Areas of expertise (comma-separated)', max_length=255, verbose_name='expertise')),
                ('website', models.URLField(blank=True, help_text='Personal or professional website', verbose_name='website')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL', verbose_name='LinkedIn')),
                ('telegram_username', models.CharField(blank=True, help_text='Telegram username without @', max_length=100, verbose_name='Telegram username')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL', verbose_name='YouTube')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether author is verified by platform', verbose_name='verified')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When author was verified', null=True, verbose_name='verified at')),
                ('total_students', models.PositiveIntegerField(default=0, help_text='Total students across all courses', verbose_name='total students')),
                ('total_courses', models.PositiveIntegerField(default=0, help_text='Total published courses', verbose_name='total courses')),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average rating across all courses', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='average rating')),
            ],
            options={
                'verbose_name': 'author profile',
                'verbose_name_plural': 'author profiles',
                'db_table': 'author_profiles',
            },
        ),
    ]
