# Generated by Django 6.0 on 2025-12-08 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='authorbalance',
            name='author',
            field=models.OneToOneField(limit_choices_to={'role': 'AUTHOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='author_balance', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='authorpayout',
            name='author',
            field=models.ForeignKey(limit_choices_to={'role': 'AUTHOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='authorpayout',
            name='processed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL, verbose_name='processed by'),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'AUTHOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddIndex(
            model_name='authorbalance',
            index=models.Index(fields=['author'], name='author_bala_author__1c593d_idx'),
        ),
        migrations.AddIndex(
            model_name='authorpayout',
            index=models.Index(fields=['author', '-created_at'], name='author_payo_author__bf5e07_idx'),
        ),
        migrations.AddIndex(
            model_name='authorpayout',
            index=models.Index(fields=['status'], name='author_payo_status_4e6563_idx'),
        ),
        migrations.AddIndex(
            model_name='authorpayout',
            index=models.Index(fields=['created_at'], name='author_payo_created_109931_idx'),
        ),
        migrations.AddIndex(
            model_name='authorprofile',
            index=models.Index(fields=['user'], name='author_prof_user_id_d1d456_idx'),
        ),
        migrations.AddIndex(
            model_name='authorprofile',
            index=models.Index(fields=['is_verified'], name='author_prof_is_veri_9b7764_idx'),
        ),
    ]
