# Generated by Django 6.0 on 2025-12-08 10:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('title', models.CharField(help_text='Course title', max_length=255, verbose_name='title')),
                ('slug', models.SlugField(help_text='URL-friendly course identifier', max_length=280, unique=True, verbose_name='slug')),
                ('description', models.TextField(help_text='Detailed course description', verbose_name='description')),
                ('short_description', models.CharField(blank=True, help_text='Brief course summary for cards', max_length=500, verbose_name='short description')),
                ('thumbnail', models.ImageField(blank=True, help_text='Course thumbnail image', null=True, upload_to='courses/thumbnails/', verbose_name='thumbnail')),
                ('trailer_url', models.URLField(blank=True, help_text='Free preview video URL (Vimeo/BunnyCDN)', verbose_name='trailer URL')),
                ('price', models.DecimalField(decimal_places=2, help_text='Course price in UZS', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='price')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Publication status', max_length=20, verbose_name='status')),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', help_text='Course difficulty level', max_length=50, verbose_name='level')),
                ('language', models.CharField(default='uz', help_text='Course language code', max_length=10, verbose_name='language')),
                ('requirements', models.TextField(blank=True, help_text='What students need to know before taking this course', verbose_name='requirements')),
                ('what_you_will_learn', models.TextField(blank=True, help_text='Key learning outcomes', verbose_name='what you will learn')),
                ('enrollment_count', models.PositiveIntegerField(default=0, help_text='Total number of enrolled students', verbose_name='enrollment count')),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average course rating', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='average rating')),
                ('review_count', models.PositiveIntegerField(default=0, help_text='Total number of reviews', verbose_name='review count')),
                ('total_duration_minutes', models.PositiveIntegerField(default=0, help_text='Total course duration in minutes', verbose_name='total duration')),
                ('published_at', models.DateTimeField(blank=True, help_text='When the course was published', null=True, verbose_name='published at')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('price_paid', models.DecimalField(decimal_places=2, help_text='Amount paid for the course in UZS', max_digits=10, verbose_name='price paid')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Course completion percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='progress')),
                ('completed', models.BooleanField(default=False, help_text='Whether student completed the course', verbose_name='completed')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the course was completed', null=True, verbose_name='completed at')),
                ('certificate_issued', models.BooleanField(default=False, help_text='Whether completion certificate was issued', verbose_name='certificate issued')),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time student accessed the course', verbose_name='last accessed')),
            ],
            options={
                'verbose_name': 'course enrollment',
                'verbose_name_plural': 'course enrollments',
                'db_table': 'course_enrollments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('title', models.CharField(help_text='Module title', max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Module description', verbose_name='description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Module display order within course', verbose_name='order')),
            ],
            options={
                'verbose_name': 'course module',
                'verbose_name_plural': 'course modules',
                'db_table': 'course_modules',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('comment', models.TextField(blank=True, help_text='Review text', verbose_name='comment')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Whether student actually purchased the course', verbose_name='verified purchase')),
                ('helpful_count', models.PositiveIntegerField(default=0, help_text='Number of users who found this review helpful', verbose_name='helpful count')),
            ],
            options={
                'verbose_name': 'course review',
                'verbose_name_plural': 'course reviews',
                'db_table': 'course_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('title', models.CharField(help_text='Assignment title', max_length=255, verbose_name='title')),
                ('description', models.TextField(help_text='Assignment instructions', verbose_name='description')),
                ('attachment', models.FileField(blank=True, help_text='Assignment files or templates', null=True, upload_to='homework/assignments/', verbose_name='attachment')),
            ],
            options={
                'verbose_name': 'homework assignment',
                'verbose_name_plural': 'homework assignments',
                'db_table': 'homework_assignments',
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('content', models.TextField(help_text='Student answer or submission text', verbose_name='submission content')),
                ('attachment', models.FileField(blank=True, help_text='Submitted files', null=True, upload_to='homework/submissions/', verbose_name='attachment')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, help_text='Grade out of 100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='grade')),
                ('feedback', models.TextField(blank=True, help_text='Teacher feedback on submission', verbose_name='feedback')),
                ('graded_at', models.DateTimeField(blank=True, help_text='When the submission was graded', null=True, verbose_name='graded at')),
            ],
            options={
                'verbose_name': 'homework submission',
                'verbose_name_plural': 'homework submissions',
                'db_table': 'homework_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('title', models.CharField(help_text='Lesson title', max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Lesson description', verbose_name='description')),
                ('video_url', models.URLField(help_text='Video URL from streaming service (Vimeo/BunnyCDN)', verbose_name='video URL')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Lesson duration in minutes', verbose_name='duration')),
                ('text_content', models.TextField(blank=True, help_text='Additional text materials displayed under video', verbose_name='text content')),
                ('attachments', models.FileField(blank=True, help_text='Downloadable materials (PDF, etc.)', null=True, upload_to='lessons/attachments/', verbose_name='attachments')),
                ('is_preview', models.BooleanField(default=False, help_text='Allow non-enrolled students to watch this lesson', verbose_name='free preview')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lesson display order within module', verbose_name='order')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
                'db_table': 'lessons',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('completed', models.BooleanField(default=False, help_text='Whether lesson is marked as complete', verbose_name='completed')),
                ('watch_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='How much of the video was watched', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='watch percentage')),
                ('last_position_seconds', models.PositiveIntegerField(default=0, help_text='Last watched position in seconds (for resume)', verbose_name='last position')),
                ('watch_time_seconds', models.PositiveIntegerField(default=0, help_text='Total time spent watching (may exceed video length)', verbose_name='total watch time')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the lesson was marked complete', null=True, verbose_name='completed at')),
            ],
            options={
                'verbose_name': 'lesson progress',
                'verbose_name_plural': 'lesson progress records',
                'db_table': 'lesson_progress',
                'ordering': ['enrollment', 'lesson'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('name', models.CharField(help_text='Category name (e.g., IT, Languages, Hobby)', max_length=100, verbose_name='name')),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Category description', verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji for display', max_length=50, verbose_name='icon')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for displaying categories', verbose_name='display order')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='courses.category', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
    ]
