# Generated by Django 6.0 on 2025-12-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file directly (MP4 recommended)', null=True, upload_to='lessons/videos/', verbose_name='video file'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Video URL from streaming service (YouTube/Vimeo/BunnyCDN)', verbose_name='video URL'),
        ),
    ]
