# Generated by Django 6.0 on 2025-12-08 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes Requested')], default='PENDING', help_text='Moderation status', max_length=20, verbose_name='status')),
                ('review_notes', models.TextField(blank=True, help_text='Reviewer notes and feedback to author', verbose_name='review notes')),
                ('rejection_reason', models.TextField(blank=True, help_text='Specific reason for rejection', verbose_name='rejection reason')),
                ('changes_requested', models.TextField(blank=True, help_text='Specific changes author needs to make', verbose_name='changes requested')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the review was completed', null=True, verbose_name='reviewed at')),
                ('quality_score', models.PositiveSmallIntegerField(blank=True, help_text='Quality score out of 100', null=True, verbose_name='quality score')),
                ('content_complete', models.BooleanField(default=False, help_text='Course has all required content', verbose_name='content complete')),
                ('video_quality_ok', models.BooleanField(default=False, help_text='Video quality meets standards', verbose_name='video quality OK')),
                ('description_adequate', models.BooleanField(default=False, help_text='Course description is clear and complete', verbose_name='description adequate')),
                ('pricing_appropriate', models.BooleanField(default=False, help_text='Course pricing is reasonable for content', verbose_name='pricing appropriate')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_history', to='courses.course', verbose_name='course')),
                ('reviewer', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_course_reviews', to=settings.AUTH_USER_MODEL, verbose_name='reviewer')),
            ],
            options={
                'verbose_name': 'course moderation',
                'verbose_name_plural': 'course moderations',
                'db_table': 'course_moderations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course', '-created_at'], name='course_mode_course__3a46fe_idx'), models.Index(fields=['status'], name='course_mode_status_e9b7a8_idx'), models.Index(fields=['reviewer'], name='course_mode_reviewe_361819_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('action_type', models.CharField(choices=[('COURSE_APPROVED', 'Course Approved'), ('COURSE_REJECTED', 'Course Rejected'), ('USER_BANNED', 'User Banned'), ('USER_UNBANNED', 'User Unbanned'), ('PAYOUT_APPROVED', 'Payout Approved'), ('PAYOUT_REJECTED', 'Payout Rejected'), ('REFUND_APPROVED', 'Refund Approved'), ('REFUND_REJECTED', 'Refund Rejected'), ('CONFIG_CHANGED', 'Configuration Changed'), ('OTHER', 'Other')], help_text='Type of action performed', max_length=30, verbose_name='action type')),
                ('description', models.TextField(help_text='Description of what was done', verbose_name='description')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of admin', null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, help_text='Browser/client user agent', max_length=500, verbose_name='user agent')),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Additional context data about the action', verbose_name='additional data')),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to=settings.AUTH_USER_MODEL, verbose_name='admin')),
                ('affected_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to='courses.course', verbose_name='affected course')),
                ('affected_user', models.ForeignKey(blank=True, help_text='User affected by this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affected_in_logs', to=settings.AUTH_USER_MODEL, verbose_name='affected user')),
            ],
            options={
                'verbose_name': 'moderation log',
                'verbose_name_plural': 'moderation logs',
                'db_table': 'moderation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', '-created_at'], name='moderation__admin_i_bb5a98_idx'), models.Index(fields=['action_type', '-created_at'], name='moderation__action__51465a_idx'), models.Index(fields=['affected_user'], name='moderation__affecte_34d314_idx'), models.Index(fields=['affected_course'], name='moderation__affecte_4c2a56_idx'), models.Index(fields=['-created_at'], name='moderation__created_f77e0e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted', null=True)),
                ('action', models.CharField(choices=[('BAN', 'Ban'), ('UNBAN', 'Unban'), ('WARNING', 'Warning'), ('SUSPEND', 'Suspend')], help_text='Moderation action taken', max_length=20, verbose_name='action')),
                ('reason', models.CharField(choices=[('SPAM', 'Spam/Advertising'), ('HARASSMENT', 'Harassment'), ('FRAUD', 'Fraudulent Activity'), ('VIOLATION', 'Terms Violation'), ('COPYRIGHT', 'Copyright Infringement'), ('OTHER', 'Other')], help_text='Reason for action', max_length=20, verbose_name='reason')),
                ('details', models.TextField(help_text='Detailed explanation of the action', verbose_name='details')),
                ('is_permanent', models.BooleanField(default=False, help_text='Whether action is permanent', verbose_name='permanent')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When temporary action expires (null if permanent)', null=True, verbose_name='expires at')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when action was taken', null=True, verbose_name='IP address')),
                ('evidence_urls', models.JSONField(blank=True, default=list, help_text='Evidence/screenshots supporting the action', verbose_name='evidence URLs')),
                ('moderator', models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='moderator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_history', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user moderation',
                'verbose_name_plural': 'user moderations',
                'db_table': 'user_moderations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_modera_user_id_37dca9_idx'), models.Index(fields=['action'], name='user_modera_action_c63b95_idx'), models.Index(fields=['moderator'], name='user_modera_moderat_e2ab30_idx'), models.Index(fields=['expires_at'], name='user_modera_expires_8a8f2e_idx')],
            },
        ),
    ]
